.gitignore
cogs/rtfm.py
cogs/utils/fuzzy.py
main.py

This is my first PR on github ever so bare with me.
Added in main.py:
- loop through cogs folder to add cogs
- bot.session (aiohttp) for rtfm
Added in cogs/utils/fuzzy.py:
- http://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/ from Rapptz/RoboDanny fuzzy 
Added in cogs/rtfm:
- necessary imports
- SphinxObjectFileReader
- parse_object_inv for getting from readthedocs.io and replacing nextcord. and nextcord.ext.commands with no extra
- build_rtfm_lookup_table for caching and getting /objects.inv from readthedocs
- do_rtfm for the main brains of rtfm, py and nextcord docs, replacing abc messageables and ext.commands, fuzzy finder and responding
- rtfm and rtfm py for actually calling do_rtfm
*lmk in nextcord discord (ooliver#6969) about anything not working, I havent …

add rtfm command and cog usability

---

cogs/rtfm.py

owner only command to delete bot._rtfm_cache
should delete all cache to reload on new changes

command to purge rtfm cache

---

main.py

#4 
This is the new pull request (which adds error handling). However, since this is a new branch and I fetched upstream, this should work and be mergeable.

Add error handling 2

---

cogs/help.py

Sending "thread is locked" may unlock the thread

Fix: =close

---

cogs/help.py

locking requires archiving for ``=close`` to work

Fix: archive help thread too

---

main.py

I updated on_command_error to include the type of error when it runs into an error that's not one of the other errors caught.

update on_command_error to include the type of error

---

cogs/etc.py
cogs/rtfm.py

Another piece of code from RoboDanny :)
Great for finding out unicode codepoint of default emojis.

Added charinfo command

---

.gitignore
cogs/etc.py
cogs/help.py
cogs/rtfm.py
main.py

This PR reformats some files because they sucked. Also adds confirmation to the help buttons when clicked the user will be asked if they really need help and a Close button in the thread for easy closing.
Please comment if anything is wrong or needs changing.

Reformat bot & Added confirmation/close to the help buttons.

---

cogs/help.py

This PR implements the `on_thread_member_remove` to auto-close threads of who the author (creator) left the thread.

Auto close thread when creator leaves.

---

cogs/help.py

I just realised I committed a few half-finished changes.
Opening a new PR to add them before the next time the bot is restarted lmao

fixed thread-close DM

---

cogs/help.py

This PR fixes threads "re-closing" when the thread was already archived and the member left or if someone pressed the Close button.

Fix threads re-closing

---

assets/helpguide.txt

use our paste service

---

cogs/stars.py

the previous one look ugly in hindsight, this pr makes it more beautiful.

Better v3 stars

---

cogs/autopaste.py

- Ignore any bot
- Don't delete the original message
- Reply instead
- AllowedMentions.none exists

Fix autopaste

---

cogs/autopaste.py

This PR auto uploads the following file types to the workbin: `.py, .js, .yml, .md, .json`.

Autopaste files to paste.nextcord.dev

---

cogs/autopaste.py

This PR adds a button with a timeout of 5 minutes to delete the message sent by the bot.
The button can be used by the author of the message, users with the `manage_messages` permission in the channel and help mods only in a help thread.

[autopaste] Added a button to delete the message

---

main.py

replace else, if, with elif

---

cogs/help.py

This adds a `=transfer` command to transfer the thread to another user.
This is tested.

Add transfer

---

cogs/docs.py

We established a while back that `rtfm` is a fairly negative/dismissive name, and that docs is better, and made docs the main name of the command in a previous PR. This PR is an addition to that which removes the rtfm terminology entirely now that the community has had time to adjust to the new command name.

feat: rename rtfm to docs

---

cogs/help.py

This PR "fixes" the close view that is sent in help threads.
Also fixes an error that occured when trying to disable a button in an archived thread.

Fix help threads

---

cogs/autopaste.py

Assume the language is python when a .txt file is uploaded in a help thread.

[autopaste] Assume language is python in help threads

---

cogs/help.py

Fix: Borked error message in close command

---

cogs/help.py

This PR fixes the thread name regex. Regex was made by @ooliver1, @DenverCoder1 and a small portion by me.
Source: https://discord.com/channels/881118111967883295/885613335062671440/954415687403716660

Fix help thread topic regex

---

cogs/autopaste.py

This PR adds support for uploading multiple and adds support for `.yaml`. And sends the data as JSON now.
Everything is tested.

[autopaste] Add support for multiple attachments

---

README.md
cogs/autopaste.py
cogs/autothread.py
cogs/bot_linking.py
cogs/database.py
cogs/discorddoc.py
cogs/docs.py
cogs/etc.py
cogs/help.py
cogs/stars.py
cogs/utils/fuzzy.py
cogs/utils/split_txtfile.py
main.py

AAAAAAAAAAAAAAAAAAA merge conflicts :(

feat: add bot linking

---

cogs/help.py

Timed out users can not interact with buttons.

---

cogs/autothread.py
cogs/stars.py

This PR adds typehinting in autothread.py and updates stars.py for code consistency across other cogs as well as adds typehinting.

Update autothread and stars

---

cogs/autopaste.py

This PR changes the delete message view interaction check to disallow the thread author from deleting the paste message and instead allow the help mod to do so (only in help threads).
This is tested.

[autopaste] Disallow thread author from deleting the message
